# Generated by Django 2.2.1 on 2019-05-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetmodel',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.DistrictModel', verbose_name='ilce'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.QuarterModel', verbose_name='Mahalle'),
        ),
    ]
