# Generated by Django 2.2.1 on 2019-05-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190528_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditToolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tool')),
            ],
            options={
                'verbose_name': 'Araclar',
                'verbose_name_plural': 'Araclar',
            },
        ),
        migrations.CreateModel(
            name='TechnologyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technology')),
            ],
            options={
                'verbose_name': 'Grafik Tasarim',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='bankmodel',
            options={'verbose_name': 'Bank Contact', 'verbose_name_plural': 'Bank Contacts'},
        ),
        migrations.AlterModelOptions(
            name='citymodel',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': '1 - Cities'},
        ),
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': 'Firm', 'verbose_name_plural': 'Firms'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='districtmodel',
            options={'ordering': ['city__name', 'name'], 'verbose_name': 'District', 'verbose_name_plural': '2 - Districtes'},
        ),
        migrations.AlterModelOptions(
            name='industrymodel',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='pricemodel',
            options={'verbose_name': 'Cost', 'verbose_name_plural': 'Costs'},
        ),
        migrations.AlterModelOptions(
            name='quartermodel',
            options={'ordering': ['district__name', 'name'], 'verbose_name': 'Quarter', 'verbose_name_plural': '3 - Quarters'},
        ),
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='streetmodel',
            options={'ordering': ['quarter__name', 'name'], 'verbose_name': 'Street', 'verbose_name_plural': '4 - Streets'},
        ),
        migrations.AlterModelOptions(
            name='taxmodel',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'All Tax'},
        ),
        migrations.RemoveField(
            model_name='citymodel',
            name='value',
        ),
        migrations.RemoveField(
            model_name='districtmodel',
            name='value',
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.CityModel', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.DistrictModel', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='quarter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.QuarterModel', verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.StreetModel', verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='account',
            field=models.TextField(max_length=255, verbose_name='Pay No'),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='branch',
            field=models.CharField(max_length=50, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='coordinates',
            field=models.TextField(blank=True, null=True, verbose_name='Coordinate'),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='order',
            field=models.IntegerField(verbose_name='Order No'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.AddressModel', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='bank',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='company.BankModel', verbose_name='Bank Info'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company_reference',
            field=models.IntegerField(verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.IndustryModel', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Company '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E Mail'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='mobile',
            field=models.CharField(max_length=10, verbose_name='Your Mobile'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(max_length=100, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='districtmodel',
            name='coordinates',
            field=models.TextField(blank=True, null=True, verbose_name='Coordinate'),
        ),
        migrations.AlterField(
            model_name='districtmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='districtmodel',
            name='order',
            field=models.IntegerField(verbose_name='Order No'),
        ),
        migrations.AlterField(
            model_name='industrymodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='industrymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.IndustryModel', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='pricemodel',
            name='daily_wage',
            field=models.FloatField(verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='quartermodel',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.CityModel', verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='quartermodel',
            name='coordinates',
            field=models.TextField(blank=True, null=True, verbose_name='Coordinate'),
        ),
        migrations.AlterField(
            model_name='quartermodel',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.DistrictModel', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='quartermodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='quartermodel',
            name='order',
            field=models.IntegerField(verbose_name='OrderNo'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.DepartmentModel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.DistrictModel', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='order',
            field=models.IntegerField(verbose_name='OrderNo'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.QuarterModel', verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='administration',
            field=models.CharField(max_length=100, verbose_name='Tax Administration'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='taxNo',
            field=models.BigIntegerField(verbose_name='Tax No'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='technologies',
            field=models.ManyToManyField(to='company.TechnologyModel', verbose_name='Technologies'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='tools',
            field=models.ManyToManyField(to='company.EditToolModel', verbose_name='Tools'),
        ),
    ]
