# Generated by Django 2.2.1 on 2019-05-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190528_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edittoolmodel',
            options={'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Ordre', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='technologymodel',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='technologymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.TechnologyModel', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.TaxModel', verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyModel', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.DepartmentModel', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_firstname',
            field=models.CharField(max_length=50, verbose_name='Fisrt Name'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_lastname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.PriceModel', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='service',
            field=models.ManyToManyField(to='company.ServiceModel', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderType',
            field=models.IntegerField(verbose_name='Order type'),
        ),
    ]
